name: Deploy Bot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2, pull code, and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/admin/finals-stat-tracker-bot/
            .venv/bin/pip install -r requirements.txt
            git pull
            sudo systemctl restart finalsbot